tolgee:
  authentication:
    enabled: true
    initial-password: admin
    initial-username: admin
    registrations-allowed: true
    # jwt-secret: my_jwt_secret
  smtp:
    auth: false
    from: Tolgee <no-reply@mydomain.com>
    host: email-smtp.regional-region.amazonaws.com
    password: 'omg/my/password'
    port: 465
    ssl-enabled: true
    username: user@company.com