version: '3'

services:
  app:
    image: tolgee/tolgee:v3.70.2
    volumes:
      - ./data:/data
      - ./config.yaml:/config.yaml # <--- this line
    ports:
      - '25432:25432'
      - '8080:8080'
    environment:
      spring.config.additional-location: file:///config.yaml # <--- this line
    env_file:
      - .env